fun main() {
    println("Введите координаты точки x")
    val x0= readln().toInt()
    println("Введите координаты точки y")
    val y0= readln().toInt()
    println("Введите координаты точки треугольника x1")
    val x1=readln().toInt()
    println("Введите координаты точки треугольника y1")
    val y1=readln().toInt()
    println("Введите координаты точки треугольника x2")
    val x2=readln().toInt()
    println("Введите координаты точки треугольника y2")
    val y2=readln().toInt()
    println("Введите координаты точки треугольника x3")
    val x3=readln().toInt()
    println("Введите координаты точки треугольника y3")
    val y3=readln().toInt()
    val a = (x1 - x0) * (y2 - y1) - (x2 - x1) * (y1 - y0)
    val b = (x2 - x0) * (y3 - y2) - (x3 - x2) * (y2 - y0)
    val c = (x3 - x0) * (y1 - y3) - (x1 - x3) * (y3 - y0)
    if ((a>=0&&b>=0&&c>=0)||(a<=0&&b<=0&&c<=0)){
        println("Входит")
    } else(println("Не входит"))
}
